#Makefile for ASGN0
#Makes the "basic cat program" without support for flags

COMPILER = mingw32-gcc.exe

catpgrm: catpgrm.c
	mingw32-gcc.exe catpgrm.c -o catpgrm.exe

clean:
	-rm -f catpgrm.exe

.PHONY: clean
